### PR TITLE
Update the spec to work with the refactor of cocoapods 0.17

### PR DESCRIPTION
**Pull request by dulacp**
A little help to get the spec working with the upcoming of `cocoapods` 0.17.
Nevertheless, like said in the [linked issue](https://github.com/CocoaPods/CocoaPods/issues/837), this is too soon to push that to the Specs repo.

### CODE REVIEW

**Comment by incanus** [comment]
Awesome, thanks for this -- will investigate.

**Comment by incanus** [comment]
Getting to this now since 0.17 is now out (four days ago).

**Comment by incanus** [comment]
This is failing for me with 0.17.1. 

```
undefined method `copy_resources_script_name' for #<Pod::Hooks::LibraryRepresentation:0x10fd19218>
```

**Comment by incanus** [comment]
Fixed in 3d2f02f etc.
